version: '3.8'

services:
  postgres-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER={PG_USER}
      - POSTGRES_PASSWORD={PG_PASSWORD}
  
  spring-app:
    image: backend-transaction-reporter:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/transactions
    depends_on:
      - postgres-db
    
  angular-app:
    build:
      context: ./tr-frontend
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      - spring-app