version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=transaction-reporter
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=40028922
    
    # env_file:
    #   - .env

    
  spring-app:
    image: backend-transaction-reporter:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/transaction-reporter
    # env_file:
    #   - .env
    depends_on:
      - postgres-db
    
  angular-app:
    build:
      context: ./tr-frontend
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      - spring-app