version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - .env
    
  spring-app:
    image: backend-transaction-reporter:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres-db
    
  angular-app:
    build:
      context: ./tr-frontend
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      - spring-app