version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=transaction-reporter-db
      - POSTGRES_USER=transaction-reporter-db_owner
      - POSTGRES_PASSWORD=v7FqiCI2KcWp
    
  spring-app:
    image: backend-transaction-reporter:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/transaction-reporter-db
    depends_on:
      - postgres-db
    
  angular-app:
    build:
      context: ./tr-frontend
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      - spring-app