package com.example.pagamentos.repository;

import java.util.List;

import org.springframework.data.repository.CrudRepository;

import com.example.pagamentos.entities.Transaction;

public interface TransactionRepository extends CrudRepository<Transaction, Long> {
    // Listing all stores in alphabetical order and displaying the most recent transactions first. The equivalent SQL command generated by Spring Data is: SELECT * FROM transacao ORDER BY store_name ASC, id DESC;
    List<Transaction> findAllByOrderByStoreNameAscIdDesc();
}
