package com.example.reporter.repository;

import java.util.List;
import java.util.UUID;

import org.springframework.data.repository.CrudRepository;

import com.example.reporter.entities.Operation;

public interface OperationRepository extends CrudRepository<Operation, UUID> {
    // Listing all stores in alphabetical order and displaying the most recent operations first. The equivalent SQL command generated by Spring Data is: SELECT * FROM operation ORDER BY store_name ASC, id DESC;
    List<Operation> findAllByOrderByStoreNameAscIdDesc();
}
