package com.example.reporter.repository;

import java.util.List;

import org.springframework.data.repository.CrudRepository;

import com.example.reporter.entities.Operation;

public interface OperationRepository extends CrudRepository<Operation, Long> {
    // Listing all stores in alphabetical order and displaying the most recent operations first. The equivalent SQL command generated by Spring Data is: SELECT * FROM operation ORDER BY op_store_name ASC, op_id DESC;
    List<Operation> findAllByOrderByOpStoreNameAscOpIdDesc();
}
